[phases.setup]
nixPkgs = ["python313", "python313Packages.pip", "pkg-config", "gcc", "libmysqlclient"]

[phases.install]
cmds = ["python3.13 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python3.13 manage.py collectstatic --noinput"]

[start]
cmd = "python3.13 -m daphne -b 0.0.0.0 -p $PORT smarthome.asgi:application"