# Generated by Django 6.0.4 on 2026-04-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('time', 'Time-based'), ('device_state', 'Device state')], max_length=20)),
                ('trigger_value', models.CharField(max_length=100)),
                ('condition_json', models.JSONField(blank=True, null=True)),
                ('action', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('action_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
